### ISSUE TITLE
Coupon get assigned even if invalid (when set automatically)

### ISSUE THREAD

**Issue by Zelig880** [tastyigniter/ti-ext-coupons#18]
**Expected behavior:**
I would like the coupon to be assigned to my cart ONLY if it is in a valid day.

**Actual behavior:**
The coupon get assigned to the card and then removed even when it is the wrong day of the week.

**Reproduce steps:**
- Create a coupon that is available only on specific days of the week
- set the coupon to autoapply
- go to the site and add an item to the cart
- the coupon will be applied and then remove (see screenshot).

**Version:**
v3.0.4-beta.27

**Additional Information:**
- in the attached screenshot, the coupone of 20% off just applied on tuesday, so it has been removed (hence the array is empty), but the discount and the actual info still show on the sidebar.

![image](https://user-images.githubusercontent.com/9040770/107707114-465a3a80-6cb9-11eb-97fc-fd13781a5f14.png)

**Comment by djtimca** [comment]
Same issue happens when the coupon is set to auto apply and the coupon is restricted by location. Applies in the cart, but doesn't appear to carry through to checkout. Just throws an error in the cart itself.

**Comment by ryanmitchell** [comment]
Yep should be fixed in the PR - I updated the code

**Comment by djtimca** [comment]
I applied the change in PR https://github.com/tastyigniter/ti-ext-coupons/pull/20 but the behaviour is still the same for location restricted coupons.

**Comment by ryanmitchell** [comment]
Should definitely work with the code I added. Are you sure you got the PR code I updated?

**Comment by djtimca** [comment]
I have the PR #20 changes - but that is just a tweak to one line as far as I can see.  I will try PR #19 to see if that works. Neither are tagged to this issue so I'm guessing a bit.

**Comment by djtimca** [comment]
Looks like PR #19 is the one that fixes this issue - tested ok on mine.
